shell = "bash -c '{}'"
default-scheme = "base24-tomorrow-night"
default-cycle-ring = "default"

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = ". \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24", "tinted8"]

[[items]]
name = "tinted-fzf"
path = "https://github.com/tinted-theming/tinted-fzf"
themes-dir = "sh"
hook = ". \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24", "tinted8"]

[[items]]
path = "https://github.com/tinted-theming/tinted-delta"
name = "tinted-delta"
themes-dir = "configs"
supported-systems = ["base16", "base24"]

hooks = ["tmux source-file ~/.config/tmux/tmux.conf"]

[[rings]]
name = "default"
schemes = ["base24-tomorrow-night", "base24-github-dark", "base24-mathias", "base24-desert", "base24-laser", "base24-blue-matrix", "base24-tokyo-night-dark"]
