name: gh
version: 2.83.2
datasource: github-releases
package: cli/cli
url: https://github.com/cli/cli/releases/download/v{version}/gh_{version}_linux_amd64.tar.gz
extract: true
checksum_source: github-release
files:
  - src: bin
    dst: .local/bin
  - src: share
    dst: .local/share
