priority_rules:
  - name: high priority
    conditions:
      - label = urgent
    priority: high
queue_rules:
  - name: urgent
    autoqueue: true
    batch_size: 1
    queue_conditions:
      - base=main
      - label=urgent
      - "-label~=^autorelease:"
      - check-success~=^Build
      - check-success~=^Test
      - -draft
    merge_method: squash
    update_method: rebase
    update_bot_account: henry-hsieh[bot]
  - name: default
    autoqueue: true
    batch_size: 1
    queue_conditions:
      - base=main
      - -label=urgent
      - "-label~=^autorelease:"
      - check-success~=^Build
      - check-success~=^Test
      - -draft
    merge_method: squash
    update_method: rebase
    update_bot_account: henry-hsieh[bot]
merge_queue:
  max_parallel_checks: 1