priority_rules:
  - name: high priority
    conditions:
      - label = urgent
    priority: high
queue_rules:
  - name: urgent
    autoqueue: true
    conditions:
      - base=main
      - label=urgent
      - "-label~=^autorelease:"
      - check-success=build
      - check-success=test
      - -draft
    merge_method: squash
    update_method: rebase
  - name: default
    autoqueue: true
    conditions:
      - base=main
      - -label=urgent
      - "-label~=^autorelease:"
      - check-success=build
      - check-success=test
      - -draft
    merge_method: squash
    update_method: rebase
merge_queue:
  max_parallel_checks: 1
