name: ruff
version: 0.15.3
datasource: github-releases
package: astral-sh/ruff
url: https://github.com/astral-sh/ruff/releases/download/{version}/ruff-x86_64-unknown-linux-gnu.tar.gz
extract: true
checksum_source: github-release
files:
  - src: ruff
    dst: .local/bin/ruff
test:
  type: version-check
