local M = {
  bash = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  c = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  cmake = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  comment = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  cpp = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  css = {
    enable = true,
    highlight = true,
    fold = false,
    indent = false,
  },
  csv = {
    enable = true,
    highlight = true,
    fold = false,
    indent = false,
  },
  diff = {
    enable = true,
    highlight = true,
    fold = true,
    indent = false,
  },
  dockerfile = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  git_config = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  git_rebase = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  gitattributes = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  gitcommit = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  gitignore = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  go = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  html = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  java = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  javadoc = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  javascript = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  jsdoc = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  json = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  json5 = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  latex = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  lua = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  luadoc = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  luap = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  make = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  markdown = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  markdown_inline = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  nu = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  objdump = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  perl = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  printf = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  python = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  query = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  regex = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  ruby = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  rust = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  strace = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  systemverilog = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  tmux = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  toml = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  typescript = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  vim = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  vimdoc = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  xml = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
  yaml = {
    enable = true,
    highlight = true,
    fold = true,
    indent = true,
  },
}

-- Load custom settings if available
pcall(require, "config.custom.treesitter")

return M
