name: lua-language-server
version: 3.17.1
datasource: github-releases
package: henry-hsieh/lua-language-server.appimage
url: https://github.com/henry-hsieh/lua-language-server.appimage/releases/download/v{version}/Lua_Language_Server-x86_64.AppImage
extract: false
checksum_source: github-release
files:
  - src: .
    dst: .local/bin/lua-language-server
    chmod: "755"
