name: tmux
version: 3.6
datasource: github-releases
package: henry-hsieh/tmux.appimage
versioning: loose
url: https://github.com/henry-hsieh/tmux.appimage/releases/download/v{version}/Tmux-x86_64.AppImage
extract: false
checksum_source: github-release
files:
  - src: .
    dst: .local/bin/tmux
    chmod: "755"
  - src: https://github.com/henry-hsieh/tmux.appimage/releases/download/v{version}/tmux.1
    dst: .local/share/man/man1/tmux.1
