name: fzf-tab-comp
version: 487cc1ea8ac98cadec8e7ca8418b5996763ed6d9
datasource: git-refs
branch: master
package: lincheney/fzf-tab-completion
files:
  - src: https://raw.githubusercontent.com/lincheney/fzf-tab-completion/{version}/bash/fzf-bash-completion.sh
    dst: .local/share/scripts/fzf-bash-completion.sh
