name: fzf-tab-comp
version: 8ba35e65bb3792759bf17c134ce04120e5940555
datasource: git-refs
branch: master
package: lincheney/fzf-tab-completion
files:
  - src: https://raw.githubusercontent.com/lincheney/fzf-tab-completion/{version}/bash/fzf-bash-completion.sh
    dst: .local/share/scripts/fzf-bash-completion.sh
test: false
