name: fd
version: 10.3.0
datasource: github-releases
package: sharkdp/fd
url: https://github.com/sharkdp/fd/releases/download/v{version}/fd-v{version}-x86_64-unknown-linux-musl.tar.gz
extract: true
checksum_source: github-release
files:
  - src: fd
    dst: .local/bin/fd
  - src: fd.1
    dst: .local/man/man1/fd.1
  - src: autocomplete/fd.bash
    dst: .local/share/bash-completion/completions/fd.bash
