name: htop
version: 3.4.1
datasource: github-releases
package: henry-hsieh/htop.appimage
url: https://github.com/henry-hsieh/htop.appimage/releases/download/v{version}/Htop-x86_64.AppImage
extract: false
checksum_source: github-release
files:
  - src: .
    dst: .local/bin/htop
    chmod: "755"
  - src: https://github.com/henry-hsieh/htop.appimage/releases/download/v{version}/htop.1
    dst: .local/man/man1/htop.1
