name: htop
version: 3.5.3
datasource: github-releases
package: henry-hsieh/htop.appimage
url: https://github.com/henry-hsieh/htop.appimage/releases/download/v{version}/Htop-x86_64.AppImage
extract: false
checksum_source: github-release
files:
  - src: .
    dst: .local/bin/htop
    chmod: "755"
  - src: https://github.com/henry-hsieh/htop.appimage/releases/download/v{version}/htop.1
    dst: .local/share/man/man1/htop.1
    sha256: 34e092f11a0396ddf4c413785dd01e4e8cce16e62f3bb053446fb4b39ccad84c
test:
  type: version-check
