name: crush
version: 0.27.0
datasource: github-releases
package: charmbracelet/crush
url: https://github.com/charmbracelet/crush/releases/download/v{version}/crush_{version}_Linux_x86_64.tar.gz
extract: true
checksum_source: github-release
files:
  - src: crush
    dst: .local/bin/crush
  - src: manpages/crush.1.gz
    dst: .local/man/man1/crush.1.gz
  - src: completions/crush.bash
    dst: .local/share/bash-completion/completions/crush.bash
  - src: https://charm.land/crush.json
    dst: .config/crush/schema.json
