name: svlangserver
version: 0e5d6b3bf96412f492efbc0d34957a662a1adb9e
datasource: git-refs
package: imc-trading/svlangserver
branch: master
init_cmds:
  - |
    mkdir -p $HOME/.local/share/personal-setup
    npm install --quiet --prefix $HOME/.local/share/personal-setup github:imc-trading/svlangserver#{version}
    ln -rsf $HOME/.local/share/personal-setup/node_modules/.bin/svlangserver $HOME/.local/bin/svlangserver
