name: rustup
version: 1.28.2
datasource: github-tags
package: rust-lang/rustup
url: https://static.rust-lang.org/rustup/archive/{version}/x86_64-unknown-linux-gnu/rustup-init
extract: false
checksum_source: https://static.rust-lang.org/rustup/archive/{version}/x86_64-unknown-linux-gnu/rustup-init.sha256
build_cmds:
  - |
    # Rustup configuration
    export CARGO_HOME={out_dir}/.local/cargo
    export RUSTUP_HOME={out_dir}/.local/rustup
    export RUSTUP_INIT_SKIP_PATH_CHECK=yes
    chmod 755 rustup-{version}
    mv rustup-{version} rustup-init
    # Install rustup stable toolchain (default)
    ./rustup-init -y -q --no-modify-path --default-toolchain stable -c rust-analyzer,rustfmt,clippy,rust-src
    # Install rustup nightly toolchain
    $CARGO_HOME/bin/rustup -q toolchain install nightly -c rust-analyzer,rustfmt,clippy,rust-src
    # Install rustup completions
    $CARGO_HOME/bin/rustup -q completions bash > {out_dir}/.local/share/bash-completion/completions/rustup.bash
    $CARGO_HOME/bin/rustup -q completions bash cargo > {out_dir}/.local/share/bash-completion/completions/cargo.bash
