name: opencode
version: 1.18.26
datasource: github-releases
package: anomalyco/opencode
url: https://github.com/anomalyco/opencode/releases/download/v{version}/opencode-linux-x64.tar.gz
extract: true
checksum_source: github-release
files:
  - src: opencode
    dst: .local/bin/opencode
  - src: https://opencode.ai/config.json
    dst: .config/opencode/schema.json
  - src: "{pkg_dir}/opencode.jsonc"
    dst: .config/opencode/opencode.jsonc
  - src: "{pkg_dir}/tui.jsonc"
    dst: .config/opencode/tui.jsonc
test:
  type: cmd
  cmd: "opencode --version && test -d \"$HOME/.config/opencode/skills/opencode-ensemble\" && test -d \"$HOME/.config/opencode/skills/uv-package-manager\""
init_cmds:
  - opencode completion > $HOME/.local/share/bash-completion/completions/opencode.bash
  - |
    bash {pkg_dir}/scripts/init.sh {version}
