name: opencode
version: 1.1.34
datasource: github-releases
package: sst/opencode
url: https://github.com/sst/opencode/releases/download/v{version}/opencode-linux-x64.tar.gz
extract: true
checksum_source: github-release
files:
  - src: opencode
    dst: .local/bin/opencode
  - src: https://opencode.ai/config.json
    dst: .config/opencode/schema.json
  - src: "{pkg_dir}/opencode.json"
    dst: .config/opencode/opencode.json
init_cmds:
  - |
    timeout 600 opencode run "/exit" -m $(opencode models opencode | head -1)
