name: uv
version: 0.9.20
datasource: github-releases
package: astral-sh/uv
url: https://github.com/astral-sh/uv/releases/download/{version}/uv-x86_64-unknown-linux-gnu.tar.gz
extract: true
checksum_source: github-release
files:
  - src: uv
    dst: .local/bin/uv
  - src: uvx
    dst: .local/bin/uvx
