name: opencode-workflows
version: "8e28cc50917708eba3d036218e332aea75067d54"
datasource: git-refs
branch: master
package: IgorWarzocha/Opencode-Workflows
url: https://github.com/IgorWarzocha/Opencode-Workflows.git
checksum_source: git-refs
files:
  - src: .
    dst: .config/opencode/opencode-workflows
build_cmds:
  - python3 {pkg_dir}/create_symlinks.py {out_dir} {pkg_dir}/workflows.json
