name: opencode-workflows
version: 1388bf98dcbfd027ac20b072fbc9a202ad4b187c
datasource: git-refs
branch: master
package: IgorWarzocha/Opencode-Workflows
url: https://github.com/IgorWarzocha/Opencode-Workflows.git
checksum_source: git-refs
files:
  - src: .
    dst: .config/opencode/opencode-workflows
test: false
build_cmds:
  - python3 {pkg_dir}/create_symlinks.py {out_dir} {pkg_dir}/workflows.json
