name: opencode-workflows
version: 6444ec4aac80ede26fed1a51832d83e3f0598026
datasource: git-refs
branch: master
package: IgorWarzocha/Opencode-Workflows
url: https://github.com/IgorWarzocha/Opencode-Workflows.git
checksum_source: git-refs
files:
  - src: .
    dst: .config/opencode/opencode-workflows
test: false
build_cmds:
  - python3 {pkg_dir}/create_symlinks.py {out_dir} {pkg_dir}/workflows.json
