name: bun
version: 1.3.6
datasource: github-releases
package: oven-sh/bun
url: https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-linux-x64.zip
extract: true
checksum_source: github-release
files:
  - src: bun
    dst: .local/bin/bun
    chmod: "755"
