name: ty
version: 0.0.34
datasource: github-releases
package: astral-sh/ty
url: https://github.com/astral-sh/ty/releases/download/{version}/ty-x86_64-unknown-linux-gnu.tar.gz
extract: true
checksum_source: github-release
files:
  - src: ty
    dst: .local/bin/ty
init_cmds:
  - ty generate-shell-completion bash > $HOME/.local/share/bash-completion/completions/ty.bash
  - ty generate-shell-completion fish > $HOME/.config/fish/completions/ty.fish
test:
  type: version-check
